// Code generated by go-swagger; DO NOT EDIT.

package waf

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/nzin/taxsi2/swagger_gen/models"
)

// PostSubmitOKCode is the HTTP code returned for type PostSubmitOK
const PostSubmitOKCode int = 200

/*
PostSubmitOK the request is legit

swagger:response postSubmitOK
*/
type PostSubmitOK struct {
}

// NewPostSubmitOK creates PostSubmitOK with default headers values
func NewPostSubmitOK() *PostSubmitOK {

	return &PostSubmitOK{}
}

// WriteResponse to the client
func (o *PostSubmitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostSubmitForbiddenCode is the HTTP code returned for type PostSubmitForbidden
const PostSubmitForbiddenCode int = 403

/*
PostSubmitForbidden the request must be blocked

swagger:response postSubmitForbidden
*/
type PostSubmitForbidden struct {
}

// NewPostSubmitForbidden creates PostSubmitForbidden with default headers values
func NewPostSubmitForbidden() *PostSubmitForbidden {

	return &PostSubmitForbidden{}
}

// WriteResponse to the client
func (o *PostSubmitForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

/*
PostSubmitDefault generic error response

swagger:response postSubmitDefault
*/
type PostSubmitDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostSubmitDefault creates PostSubmitDefault with default headers values
func NewPostSubmitDefault(code int) *PostSubmitDefault {
	if code <= 0 {
		code = 500
	}

	return &PostSubmitDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post submit default response
func (o *PostSubmitDefault) WithStatusCode(code int) *PostSubmitDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post submit default response
func (o *PostSubmitDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post submit default response
func (o *PostSubmitDefault) WithPayload(payload *models.Error) *PostSubmitDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post submit default response
func (o *PostSubmitDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSubmitDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
