swagger: '2.0'
info:
  description: >
    taxsi2 is a WAF server application The base path for all the APIs is
    "/api/v1".
  title: taxsi2
  version: 1.0.0
tags:
  - name: health
    description: Check if taxsi2 is healthy
x-tagGroups:
  - name: taxsi2 Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
  - name: WAF
    tags:
      - waf
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /health:
    get:
      tags:
        - health
      operationId: getHealth
      description: Check if taxsi2 is healthy
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /submit:
    post:
      tags:
        - waf
      operationId: postSubmit
      description: Submit a request payload to analyze
      consumes:
        - application/octet-stream
      parameters:
        - name: request
          in: body
          description: The request payload in binary format
          required: true
          schema:
            type: string
            format: binary
      responses:
        '200':
          description: the request is legit
        '403':
          description: the request must be blocked
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  health:
    type: object
    properties:
      status:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
