// Code generated by go-swagger; DO NOT EDIT.

// Package restapi taxsi2
//
//	taxsi2 is a WAF server application The base path for all the APIs is "/api/v1".
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
